server:
  port: 8080
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:1001/
          predicates:
            - Path=/api/user/**, /api/appointmentService/**
        - id: appointment-service
          uri:  http://localhost:1002/
          predicates:
            - Path=/api/appointment/**

